### ISSUE TITLE
Remove operation for SAI_OBJECT_TYPE_IPSEC_PORT fails but Create passes, getting SAI_STATUS_OBJECT_IN_USE error

### ISSUE THREAD

**Issue by selldinesh** [opencomputeproject/SAI-Challenger#186] opened 2023-08-28 17:54 UTC
Added the following script
`from pprint import pprint

class TestSaiIpsecPort:
    # object with parent SAI_OBJECT_TYPE_PORT

    def test_ipsec_port_create(self, npu):
        commands = [
            {
                'name': 'port_1',
                'op': 'create',
                'type': 'SAI_OBJECT_TYPE_PORT',
                'attributes': [
                    'SAI_PORT_ATTR_HW_LANE_LIST',
                    '2:10,11',
                    'SAI_PORT_ATTR_SPEED',
                    '10',
                ],
            },
            {
                'name': 'ipsec_port_1',
                'op': 'create',
                'type': 'SAI_OBJECT_TYPE_IPSEC_PORT',
                'attributes': [
                    'SAI_IPSEC_PORT_ATTR_PORT_ID',
                    '$port_1',
                    'SAI_IPSEC_PORT_ATTR_NATIVE_VLAN_ID',
                    '10',
                ],
            },
        ]

        results = [*npu.process_commands(commands)]
        print('======= SAI commands RETURN values create =======')
        pprint(results)
        assert all(results), 'Create error'

    def test_ipsec_port_remove(self, npu):
        commands = [
            {'name': 'ipsec_port_1', 'op': 'remove'},
            {'name': 'port_1', 'op': 'remove'},
        ]

        results = [*npu.process_commands(commands)]
        print('======= SAI commands RETURN values remove =======')
        pprint(results)
        assert all(
            [result == 'SAI_STATUS_SUCCESS' for result in results]
        ), 'Remove error'
`

from the CI/CD pipeline logs create operation passed but the remove operation fails with SAI_STATUS_OBJECT_IN_USE error.

CI/CD workflow log

`>       results = [*npu.process_commands(commands)]

api/test_ipsec_port.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:212: in process_commands
    yield from map(self.command_processor.process_command, commands)
/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:146: in process_command
    return self.sai.remove(obj_id)
/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:239: in remove
    return self.sai_client.remove(obj, do_assert)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sai_client.sai_redis_client.sai_redis_client.SaiRedisClient object at 0x7fb[38](https://github.com/selldinesh/SAI-Challenger/actions/runs/5946048508/job/16126030079#step:13:39)3[40](https://github.com/selldinesh/SAI-Challenger/actions/runs/5946048508/job/16126030079#step:13:41)f780>
obj = 'SAI_OBJECT_TYPE_PORT:oid:0x10000000005c9', do_assert = True

    def remove(self, obj, do_assert=True):
        if obj.startswith("oid:"):
            assert self.vid_to_rid(obj), f"Unable to retrieve RID by VID {obj}"
            obj = self.vid_to_type(obj) + ":" + obj
        assert obj.startswith("SAI_OBJECT_TYPE_")
        obj = obj.replace(" ", "")
    
        status = self.operate(obj, "{}", "Dremove")
        status[2] = status[2].decode("utf-8")
        if do_assert:
>           assert status[2] == 'SAI_STATUS_SUCCESS', f"remove({obj}) --> {status}"
E           AssertionError: remove(SAI_OBJECT_TYPE_PORT:oid:0x10000000005c9) --> [b'Sgetresponse', b'[]', 'SAI_STATUS_OBJECT_IN_USE']`

**Comment by andriy-kokhan** [comment] 2023-08-29 07:05
Since you've mentioned that the issue is observed in CI/CD pipeline, I'm assuming the test has been executed on SONiC VS only. The /var/log/syslog provides much more information:
```
Aug 29 06:33:30 b3ac4072fb6b syncd: :- onPostPortCreate: discovered 43 new objects (including port) after creating port VID: oid:0x10000000005c9
Aug 29 06:33:30 b3ac4072fb6b syncd: :- onPostPortCreate: putting ALL new discovered objects to redis for port oid:0x10000000005c9
Aug 29 06:33:30 b3ac4072fb6b syncd: :- redisUpdatePortLaneMap: added 2 lanes to redis lane map for port RID oid:0x100000021
Aug 29 06:33:30 b3ac4072fb6b syncd: :- collectPortRelatedObjects: obtained 42 port oid:0x100000021 related RIDs
Aug 29 06:33:30 b3ac4072fb6b syncd: :- meta_port_remove_validation: all objects related to port oid:0x100000021 are in default state, can be remove
Aug 29 06:33:30 b3ac4072fb6b syncd: :- check_port_dependencies: port oid:0x100000021 found, for removal
Aug 29 06:33:30 b3ac4072fb6b syncd: :- check_port_reference_count: port id oid:0x100000021 is in use on port serdes oid:0x5700000020
Aug 29 06:33:30 b3ac4072fb6b syncd: :- check_port_dependencies: port oid:0x100000021 reference count IS NOT ZERO, can't remove, remove dependencies first
Aug 29 06:33:30 b3ac4072fb6b syncd: :- removePort: port oid:0x100000021 still have some active dependencies, can't remove
Aug 29 06:33:30 b3ac4072fb6b syncd: :- remove: remove status: SAI_STATUS_OBJECT_IN_USE
Aug 29 06:33:30 b3ac4072fb6b syncd: :- sendApiResponse: api SAI_COMMON_API_REMOVE failed in syncd mode: SAI_STATUS_OBJECT_IN_USE
```
As you can see, the port is referred by a serdes object.
But actually, this TC has even bigger issue - the port was implicitly created during Switch Init - that is the default behavior of SONiC VS. So, you should not try to create a port without making sure it's not created at the moment. Ideally, the port creation request is expected to be failing but looks like SONiC VS implementation violates this...

The key idea of SAI-C is that the ports are either explicitly created on Switch Init or create based on provided HWSKU. In both case `objects_discovery()` helps to retrieve `PORT_{idx}` that should be used in TCs.

So, closing this ticket as "Not An Issue".

**Closed by andriy-kokhan** 2023-08-29 07:05 UTC
